### ISSUE TITLE
Implement API to customize loop.create_task()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python/asyncio#208]
```
In asyncio we try to avoid using or encouraging to use subclassing as APIs. 
However, the only way to customize the recently added 'create_task()' method is 
to subclass event loops, which is not always convenient. 

An example of this is the greenio library, which provides a subclassed 
'asyncio.SelectorEventLoop' and a custom event loop policy just for the sake of 
customizing the 'create_task' method. Users of other kinds of event loops will 
have to do the same subclassing dance.

I propose to add two new API methods to event loops (similarly to what we did 
for custom handlers):

- set_task_factory(callable)
- default_task_factory(coro)

Here's a link to codereview: https://codereview.appspot.com/148240043
```

Original issue reported on code.google.com by `yseliva...@gmail.com` on 27 Sep 2014 at 5:09

**Comment by 1st1** [comment]
Guido, Victor,

I really need this feature. This is the only last thing that requires subclassing the loop.

I propose to add one just *one* new method to event loop API: set_task_factory.  I don't think that event loop policy is a good place for it.

- set_task_factory(factory) sets the factory
- set_task_factory(None) tells the loop that it can use the default factory

If you're OK with this, I'll write a patch and make a PR.

**Comment by gvanrossum** [comment]
I thought it was this *and* the DNS lookup? :-)

Anyway, I'm fine with this. We should probably also have a get_task_factory() just so it can be managed in a stack-wise fashion if one really wishes.

**Comment by 1st1** [comment]
:)  Alright, I'll make a PR soon!

**Comment by 1st1** [comment]
Closing the issue now.
