### ISSUE TITLE
Rename the Github project to asyncio

### ISSUE THREAD

**Issue by haypo** [python/asyncio#230]
It's not easy to explain the difference between tulip and asyncio. On PyPI, the tulip project is called... asyncio. The Python module is asyncio ("import asyncio").

Why not simply renaming the Github project to asyncio and stop using the name "tulip"?

Note: https://pypi.python.org/pypi/tulip is unrelated to asyncio...

**Comment by asvetlov** [comment]
+1

On Tue, Apr 14, 2015 at 10:18 AM, Victor Stinner <notifications@github.com>
wrote:

> It's not easy to explain the difference between tulip and asyncio. On
> PyPI, the tulip project is called... asyncio. The Python module is asyncio
> ("import asyncio").
>
> Why not simply renaming the Github project to asyncio and stop using the
> name "tulip"?
>
> Note: https://pypi.python.org/pypi/tulip is unrelated to asyncio...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/tulip/issues/230>.
>



-- 
Thanks,
Andrew Svetlov

**Comment by GMLudo** [comment]
I had the same feeling, +1 to change that.

**Comment by gvanrossum** [comment]
+1

**Comment by asvetlov** [comment]
Renamed to asyncio: https://github.com/python/asyncio

**Comment by GMLudo** [comment]
I've also renamed the team.

**Comment by gvanrossum** [comment]
Thanks!
