### ISSUE TITLE
Enable Travis-CI for AsyncIO project

### ISSUE THREAD

**Issue by GMLudo** [python/asyncio#232]
If no one objects, I can enable Travis-CI for AsyncIO project, to launch automatically tests on each pull request and commits.
Apparently, it should also possible to enable Mac OS X and Windows tests support via others services, need to dig.

**Comment by gvanrossum** [comment]
I won't object! I have no idea what that even means (in more detail than "automated tests") but I expect I'll find out soon enough. :-)

**Comment by 1st1** [comment]
I've enabled the integration in e3216b8043
Should we embed travis' build badge in the README file?

**Comment by gvanrossum** [comment]
I have no idea what that even means. Who benefits from that? Recall that
the README is also included in the source tarball as the first thing people
read.

On Mon, May 11, 2015 at 12:25 PM, Yury Selivanov <notifications@github.com>
wrote:

> I've enabled the integration in e3216b8
> <https://github.com/python/asyncio/commit/e3216b80438bf42abb76c99b034eb03b2768018d>
> Should we embed travis' build badge in the README file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/asyncio/issues/232#issuecomment-101024310>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by 1st1** [comment]
The integration itself is handy as it automatically tests the PRs and tells if tests are passing (or not). I structured the current config file to run tests in 3.3 and 3.4 in production and in debug modes.

As for badge in README file -- take a look at https://github.com/1st1/greenio
It's useful for small unknown packages, as it gives the impression that the project is alive and has unittests ;)  For asyncio we probably don't need this.

**Comment by GMLudo** [comment]
Thank you a lot @1st1 to do that, it's an item that I can remove from my todo-list during my next holidays.
To be really honest with you, I've secretly hope that somebody else takes the lead of this issue: since PyCON, a lot of stuff change around me.

It's why I love OpenSource: Contrary at work, the procrastination is a good thing  in OpenSource World ;-)

Personally, I've vote to add a badge for the build status.

BTW, I've back to my mind to add also [AppVeyor](http://www.appveyor.com/) to launch tests on Windows: We have certainly more risks that we break something on Windows, because we have certainly very few developers on Windows.
For that, I recommend to watch the presentation of @ogrisel during PyCON 15:
* https://speakerdeck.com/ogrisel/build-and-test-wheel-packages-on-linux-osx-and-windows
* https://www.youtube.com/watch?v=d-p6lJJObLU

Again, if it's a candy for somebody else, be my guest, or I'll do that during my next holidays.

**Comment by 1st1** [comment]
@GMLudo NP. Please open a separate issue for AppVeyor. Although I wouldn't do it right now, let's wait a bit and see how travis integration turns out.
