### ISSUE TITLE
Gather: Optionally cancel all children on first raised exception

### ISSUE THREAD

**Issue by lgrahl** [python/asyncio#238]
I'm running two separate coroutines on a websockets connection by using ``asyncio.gather``. One sends keep alive messages (*ping*) and the other one handles messages on the connection. If the *ping* times out, the connection should be closed. And if the connection closes, sending keep alive messages is pointless. I'm raising an exception when the *ping* times out and I thought that this would cancel the other task as well. Turns out, it doesn't.

Now, here comes the problem: Since ``asyncio.gather`` handles the coroutines in self-created tasks, there is no way to cancel them any more from the outside (well, at least not without accessing private members). Cancelling the returned future will not work either because the future is marked as ``done``.

I propose a keyword argument that could be named ``exceptions_cancel_tasks`` for ``asyncio.gather``. I'll create a pull request shortly.

**Comment by asvetlov** [comment]
I think you may manually wrap your coroutines into tasks by `async()` calls and cancel non-cancelled yet tasks on getting exception from `gather()`.

**Comment by lgrahl** [comment]
Good point. But I have the feeling that this is not an unusual case: All tasks rely on each other and if one raises an exception, the others should be cancelled.

My case is a bit more unusual because I need to cancel both tasks in case of an exception **and** if one task returns. So, it turned out, I can't use gather. However, I've opened a pull request for the described case above.

**Comment by gvanrossum** [comment]
I'm confused. Do you want this to be added to upstream or are you happy using your forked version?

**Comment by lgrahl** [comment]
Uh, sorry, about that. My intention was to make a pull request and not just fork it.

I think it is useful enough to add it to the upstream but I'm sure you guys have a better overview.

**Comment by lgrahl** [comment]
I've closed the pull request because I agree that my proposal isn't the way to go. I'm going for the solution suggested by @asvetlov (thanks!).
