### ISSUE TITLE
yield from coro() in comprehensions

### ISSUE THREAD

**Issue by ilevkivskyi** [python/asyncio#240]
I would like to draw your attention to https://bugs.python.org/issue10544. In short, `yield` and `yield from` are bound inside a comprehension and not to the containing generator. Moreover, `[yield from coro() for i in lst]` is a valid expression outside a function definition. 

This bug is two years in "needs patch" stage, but a patch has never been submitted.

Before PEP 3156 this was a rare bug. But now, replacing a `for` loop with a comprehension inside an asyncio coroutine will lead to subtle bugs and confusing behaviour, see for example: http://stackoverflow.com/questions/29334054/why-am-i-getting-different-results-when-using-a-list-comprehension-with-coroutin

**Comment by Lucretiel** [comment]
Question: would a fix for this ONLY apply to list comprehensions (and other non-lazy comprehensions, like dict/set)? It *might* create inconsistent behavior the the generator comprehension, which binds the expression. For instance, consider what the result here would be:

    def foo():
        x = (yield from coro(i) for i in range(10))
        return x

Those `yield from`s have to bind somewhere, but it doesn't make sense for them to bind to `foo`, since `foo` returns before they can be evaluated.

**Comment by ilevkivskyi** [comment]
In my opinion `yield` inside generator comprehensions should be prohibited. Indeed, what you tell is true, but the current behavior is not bettter:
```python
g = ((yield i) for i in range(3))
for i in g:
    print(i)
```
prints
```python
0
None
1
None
2
None
```
That does not make much sense IMO.

**Comment by Lucretiel** [comment]
Yeah it's bizarre. It makes sense if you thing of generator expressions as a local function definition:

    (expr for var in iter if pred)

becomes

    for var in iter:
        if pred:
            yield expr

So if `expr` is a `yield` or `yield from` expression, it is run in the local generator context:

    ((yield i) for i in range(3)) ->
    for i in range(3):
        yield (yield i)

I agree that it should probably be prohibited, though. I can't think of a single case where you would want this behavior.

**Comment by asvetlov** [comment]
PEP 492 (accepted) proposes new syntax for asynchronous coroutines.

It also have a concept for [asynchronous iterators](https://www.python.org/dev/peps/pep-0492/#asynchronous-iterators-and-async-for)

Asynchronous generators as well as asynchronous comprehensions are subjects to Python 3.6 maybe.
