### ISSUE TITLE
loop.stop() uses loop.call_soon()

### ISSUE THREAD

**Issue by 1st1** [python/asyncio#244]
Can we use `loop.call_soon_threadsafe()` from `loop.stop()` so that it's easier to stop a loop from another thread?

**Comment by gvanrossum** [comment]
Hm, I would really prefer to the rule "when touching a loop from another thread you must use call_soon_threadsafe()". Is this really so common for you that you don't want to write `loop.call_soon_threadsafe(loop.stop)`?

**Comment by 1st1** [comment]
`loop.call_soon_threadsafe(loop.stop)` is an elegant solution. The rule also makes a lot of sense.

I'm not sure if it's a common thing... But I've just spent a lot of time debugging why one of my scripts hanged occasionally.

**Comment by gvanrossum** [comment]
Isn't there a debug check in call_soon() that you're calling it only from
the thread that owns the loop?

On Mon, May 11, 2015 at 4:14 PM, Yury Selivanov <notifications@github.com>
wrote:

> loop.call_soon_threadsafe(loop.stop) is an elegant solution. The rule
> also makes a lot of sense.
>
> I'm not sure if it's a common thing... But I've just spent a lot of time
> debugging why one of my scripts hanged occasionally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/asyncio/issues/244#issuecomment-101072125>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by 1st1** [comment]
There is one. I guess you're right, we don't need this change. Closing the issue.
