### ISSUE TITLE
Changing select timeout of BaseEventLoop?

### ISSUE THREAD

**Issue by akloster** [python/asyncio#247]
In some foreign event loops, especially Blender, Kivy and Jupyter,  I was able to run asyncio code quite successfully with a very dirty trick. I copied the _run_once method of the BaseEventLoop class into my own code, and changed only one line, setting the default timeout to a small value. Then I would use whatever means the foreign event loop has to call _run_once and ensure that the other event loop runs smoothly. 

While that works, there are some obvious problems. Shouldn't the default timeout for the select call be configurable? Is there a cleaner way to use asyncio in essentially "polling" mode?

The polling method I use certainly isn't the most efficient, but it works well. I'm posting the Issue here because I think that either there is no documentation how to use a polling loop, the default timeout should be made configurable, or I'm completely misunderstanding how asyncio loops are supposed to work.

**Comment by asvetlov** [comment]
I guess to 
1. Create custom selector derived from selectors.DefaultSelector.
2. Override `.select(timeout=None) method with reduce timeout to reasonable small value.
3. Instantiate event loop directly by `asyncio.set_event_loop(asyncio.SelectorEventLoop(CustomSelector()))` 

The way doesn't require any `asyncio` code change.

**Comment by gvanrossum** [comment]
Alternatively, you can make a function that causes itself to be queued to be called .1 sec later using loop.call_later().

**Comment by asvetlov** [comment]
@gvanrossum your way is better.

**Comment by akloster** [comment]
I tried the call_later method in a few tests, and it seems to work. I'll have to see if it still works when the coroutines get more complicated.

The main issue why I can't just implement a specific Event Loop for Kivy, Blender or the Jupyter Kernel is that their event loops don't do asynchronous IO as far as I can determine (I may be wrong). The selector loops from asyncio solve that problem nicely, though.

Thank you both for your input!

**Comment by asvetlov** [comment]
Close the issue
