### ISSUE TITLE
Mixed threaded-asynchronous queue

### ISSUE THREAD

**Issue by asvetlov** [python/asyncio#249]
We discussed the concept before in [tulip google group](https://groups.google.com/forum/#!topic/python-tulip/RPOEwJ0T_F0).

I've implemented [mixedqueue](https://github.com/asvetlov/mixedqueue) library. The API has sync and async parts:
```
q = mixedqueue.Queue(maxsize=25, loop=self.loop)

# sync api
q.sync_queue.put(5)
ret = q.sync_queue.get_nowait()

# async api
ret = yield from q.async_queue.get()
yield from q.async_queue.put(15)
```

Both sync and async API are synchronized, sync one should be used from threads (or `loop.run_in_executor()`), async is for coroutines.

Suggestions for API and namings are welcome.

**Comment by ajdavis** [comment]
Neat!
