### ISSUE TITLE
Got InvalidStateError on timeout

### ISSUE THREAD

**Issue by dronnix** [python/asyncio#255]
Hi!
Just run:
```python
#!/usr/bin/env python3

import asyncio


@asyncio.coroutine
def foo(msg, sleep_time=0.017):
    try:
        yield from asyncio.wait_for(asyncio.sleep(sleep_time), 0.019)
        print(msg, 'Finished')
    except asyncio.TimeoutError:
        print(msg, 'Timed out')


def main():
    loop = asyncio.get_event_loop()
    tasks = [foo(i) for i in range(1, 128)]
    loop.run_until_complete(asyncio.wait(tasks))
    loop.close()

if __name__ == '__main__':
    main()
```
And got :
```python
Exception in callback <bound method Future.set_result of Future<CANCELLED>>(None,)
handle: TimerHandle(403207.779384189, <bound method Future.set_result of Future<CANCELLED>>, (None,))
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/futures.py", line 298, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: CANCELLED: Future<CANCELLED>
```
Seems like a kind of syncronization issue.

**Comment by gvanrossum** [comment]
Sorry, I can't repro. I wonder if you're using an old version of Python or
asyncio? What Python version is that? Can you copy/paste the body of the
sleep() function in asyncio/tasks.py? (The question I'm trying to answer
is, what is the callback that's trying to call set_result. It looks like
set_result itself is the callback. But sleep() doesn't use that -- it uses
an internal Future method named _set_result_unless_cancelled. But perhaps
in the past that was just using set_result and that would explain your
traceback.

Perhaps upgrading asyncio or Python 3 will solve your problem?

**Comment by dronnix** [comment]
You are right, the reason is old version of asyncio. Sorry for wasting your time and thank you.
