### ISSUE TITLE
Why no context managers?

### ISSUE THREAD

**Issue by Zearin** [python/asyncio#261]
(I have been reading up on asyncio lately, but I am still quite new, so sorry if the follow question is naïve.)

Since `asyncio.futures` is modeled on `concurrent.futures` as closely as possible, why isn’t there support for using asyncio’s `Future` or `Task` context managers?

_(**My reason for asking:** I’ve watched many of Guido’s talks on Tulip/asyncio, and I realize that it was attempting to be as neutral and accessible to as many platforms and existing async libraries as possible.  Therefore, I think I am beginning to understand a small part of asyncio, but I still find it pretty overwhelming.  In contrast, I found the context manager syntax of `concurrent.futures` easier to learn, and more pleasant to read and write.)_

**Comment by asvetlov** [comment]
1. Asynchronous context managers are not supported until Python 3.5 (PEP 492, `async with` statement).
2. While `asyncio.Future` is crucial building block the end user usually use it very rare. `yield from`/`await`  is more common concept.

**Comment by gvanrossum** [comment]
I'm not even sure what the question is. The only documented use of context managers in concurrent.futures is about Executor objects, not about Futures. You can write
```
with ThreadPoolExecutor(...) as executor:
    f = executor.submit(...)
    ...use f.result()...
```
and it will shut down the executor. See https://docs.python.org/3/library/concurrent.futures.html .

But the only purpose of the with-statement here is to call shutdown() on the executor -- waiting for the Future's result is done implicitly in executor land by calling result().

The asyncio equivalent would be something like
```
with asyncio.new_event_loop():
    ...use the loop for stuf...
```
and at the end of the with-statement the newly created event loop would be close and removed as the current event loop. But that's not really a recommended pattern -- you're just supposed to use `run_forever()`.

I think the OP should just find an asyncio tutorial and follow some more of the examples; I don't think there's an actionable feature request here.
