### ISSUE TITLE
Asyncio, task's booleanreturn value is printed as a set/tuple

### ISSUE THREAD

**Issue by madhavan020985** [python/asyncio#262]
````
loop = asyncio.get_event_loop()
tasks = [
    asyncio.ensure_future(factorial("A", 2))]
ret = loop.run_until_complete(asyncio.wait(tasks))
print str(ret)
loop.close()
````
When i print the task's return value, instead of printing just the value, True, it prints a tuple as,
````
  (set([<Task finished coro=<factorial() done, defined at asy.py:7> result=True>]), set([]))
````
Complete code is at github - https://github.com/madhavan020985/miscFiles/blob/master/asy.py#L22

I am interested in only the boolean value, True.. How can i extract it from inside, Task<result=True>...
And again, why does it return two values inside the tuple since i gave only one task. set([]) as second value, does it mean something?

**Comment by asvetlov** [comment]
[`asyncio.wait()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) returns two sets: finished futures and pending ones.
Probably you need `asyncio.gather()` or in case of waiting the single coroutine just `loop.run_until_complete(coro())`.

**Comment by madhavan020985** [comment]
awesome
