### ISSUE TITLE
Does asycio.Semaphore have the same bug as asyncio.Queue?

### ISSUE THREAD

**Issue by gvanrossum** [python/asyncio#270]
Check out the last paragraph of https://github.com/python/asyncio/pull/269#issuecomment-143466942:

"""
Looking over the locks code, I also noticed that async.Semaphore (which can be thought of as a queue without data) uses the approach I sketched above (waking up only one waiter at a time), but without reawakening another waiter when a waiter is cancelled after its future was marked done. So I expect it can be shown to have the same bug.
"""

All we need to do now is write a test that reproduces this issue.

**Comment by gvanrossum** [comment]
The scenario would be something like this: have two tasks both blocked in acquire(); have one release() call; then, before the event loop runs the waiting task that was woken up, cancel it; the other waiting task is then just hanging even though the semaphore's semantics would allow it to proceed.

(In the Queue class we've struggled with this and similar scenarios in the opposite direction; the symptoms could be lost items, deadlock, or (in 3.5.0) assertions failing.

**Comment by manipopopo** [comment]
I try to address the issue in #271 .

**Comment by gvanrossum** [comment]
Closed by #271.
