### ISSUE TITLE
What stands behind bufsize == 0 enforcement in subprocess pipes?

### ISSUE THREAD

**Issue by neumond** [python/asyncio#272]
I see the issue https://github.com/python/asyncio/issues/119 but see no explanation. In practice I have annoying buffering (4kbytes or so, Linux, py3.4) which disallows me to get stdout lines as they actually appear. Which is very strange if you recall that bufsize forced to be 0 (behaviour is more like bufsize = -1).

**Comment by gvanrossum** [comment]
Are you sure the buffering is in asyncio and not in the subprocess whose
stdout you are trying to read?

On Sunday, September 27, 2015, Vitalik Verhovodov <notifications@github.com>
wrote:

> I see the issue #119 <https://github.com/python/asyncio/issues/119> but
> see no explanation. In practice I have annoying buffering (4kbytes or so,
> Linux, py3.4) which disallows me to get stdout lines as they actually
> appear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/asyncio/issues/272>.
>


-- 
--Guido van Rossum (on iPad)

**Comment by neumond** [comment]
Oh, yes, didn't expect usual print() will buffer being connected to pipe. Calling sys.stdout.flush() solved the problem.

```python
from time import sleep
import sys

class Unbuffered(object):
    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def __getattr__(self, attr):
        return getattr(self.stream, attr)

sys.stdout = Unbuffered(sys.stdout)

for i in range(100):
    print(i)
    sleep(1)
```

**Comment by gvanrossum** [comment]
It's standard Unix behavior: output is buffered by default unless connected to a tty device (which a pipe is not). In Python 3 you can also use print(blah, flush=True).
