### ISSUE TITLE
Wrong repr for StreamReader

### ISSUE THREAD

**Issue by asvetlov** [python/asyncio#275]
I believe in line https://github.com/python/asyncio/blob/master/asyncio/streams.py#L327 we should use length of buffer, not info

**Comment by gvanrossum** [comment]
Oops, indeed. Can you fix it?

**Comment by asvetlov** [comment]
Sure!

**Comment by asvetlov** [comment]
Done

**Comment by asvetlov** [comment]
See e42b621ecdf4b37d1f709a5a8a2bfaee684ed72d for actual commit

**Comment by gvanrossum** [comment]
Thanks!

--Guido (on mobile)
