### ISSUE TITLE
Support both async context manager and awaitable in the same place

### ISSUE THREAD

**Issue by asvetlov** [python/asyncio#277]
This is long enough story, please be patient.

I've added pep492 support to aiohttp client api.

Prelude
----------

Initially we had client request call like

    client = aiohttp.ClientSession(loop=loop)
    resp = yield from client.request('GET', url)

or even 

    resp = yield from aiohttp.get(url)

We support bare `yield from aiohttp.request('GET', url)` and family also but these shortcuts work over `ClientSession` now so let's forget about shortcuts.

I've added next step:

    resp = await client.get(url)
    async with resp:
        ...  # do your work on response object

The motivation is: HTTP response should be closed gracefully (`await resp.release()`) to support HTTP keep-alives. Everything works fine.

But I would have even more convenient API:

    async with client.get(url) as resp:
         ...

with keeping ability to use old-good `resp = await client.get(url)`. 
Backward compatibility matters and so on.

Consequently `.get(...)` method cannot be coroutine but should be regular function returning an object which is *support both protocols: coroutine and async context manager*.

Following the way I've got something like:

    def get(self, url):
         return _ContextManager(self._request('GET', url))

where `self._request(...)` is actual coroutine which performs HTTP request and

    class _ContextManager:
         def __init__(self, coro):
               self._coro = coro

         @asyncio.coroutine
         def __iter__(self):
               yield from self._coro

         def __await__(self):
               yield from self._coro

         @asyncio.coroutine
         def __aenter__(self):
               self._resp = yield from self._coro

         @asyncio.coroutie
         def __aexit__(self, exc, val, tb):
              if exc is None:
                  yield from self._resp.release()
              else:
                   # on exception we can just drop connection without returning response to pool
                   self._resp.close()  

Thank you for reading up to the point.

Problem
------------ 

in `aiohttp` docs we declared the `loop.run_until_complete(client.get(url))` is a legal construction.

`run_until_complete` calls `ensure_future()` which do perform checks for `isinstance(_ContextManager, Future)` (obviously not) and `iscoroutine(_ContextManager(...))`.

Well, I've found I should derive `_ContextManager` from `collections.abc.Coroutine` and implement  `.send`, `.throw` and `.close`. 

There is my final `_ContextManager` implementation https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L422-L464 

That's satisfies py3.5 requirements well enough but for py3.4 there is no `collections.abc.Coroutine` but `asyncio.coroutines._COROUTINE_TYPES` present.
For keeping back compatibility I was forced to add the trick `coroutines._COROUTINE_TYPES += (_RequestContextManager,)` (https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client.py#L467-L472)

Conclusion
---------------

I can avoid tricky hack by forcing

    async with await client.get(url) as resp:
         ... 

but I believe three keyword in the line looks ugly.
Just 

    async with client.get(url) as resp:
         ... 

should be enough: the code explicitly assumes that we have two *yield points* -- the first before preforming code block and the second on exit from.

Maybe relaxing the rule for `ensure_future()` will help?
Sorry, I have no clean idea but I definitely need *awaitable*, *async context manageable* and *run-until-complete-aware* object concept.

P.S.
------

We have subtle backward incompatibility in 3.5.

Before for `asyncio.locks` I was able to write

    locked = loop.run_until_complete(lock)
    with  locked:
        ... 

Now it's impossible.

**Comment by gvanrossum** [comment]
I agree about your ease of use requirement. I don't think the monkeypatch of `coroutines._COROUTINE_TYPES` is so bad, since it's only for backward compatibility with 3.4. I don't care about the locks incompatibility -- asyncio doesn't care (yet) about backward compatibility in all corner cases, it's still provisional in 3.5. (We'll have to stop doing this in 3.6.)

**Comment by asvetlov** [comment]
@gvanrossum thanks

**Comment by 1st1** [comment]
@asvetlov Since we only have `async with` since 3.5, I think you can avoid monkey patching if you do something akin to:

```python
def get(*args, **kwargs):
    if PY35:
        return AsyncWithWrapper(_get(*args, **kwargs))
    else:
        return _get(*args, **kwargs)
```

**Comment by asvetlov** [comment]
@1st1 yoe, it can solve my problem.
But isn't requirement to implement `.send()`, `.throw()` and `.close()` too burden?

**Comment by 1st1** [comment]
> But isn't requirement to implement .send(), .throw() and .close() too burden?

I think you're right here.  Please see PR #278.
