### ISSUE TITLE
examples cachesvr.py run have the address in use error

### ISSUE THREAD

**Issue by a358003542** [python/asyncio#300]
I have struggled it for a while , and change the default host to 127.0.0.1 will take away this error.

**Comment by gvanrossum** [comment]
I'm confused -- since the default is currently 'localhost' and localhost is just the name for 127.0.0.1, how does this change anything?

**Comment by GMLudo** [comment]
Could you show us /etc/hosts content ?

**Comment by a358003542** [comment]
my hosts file has the line : 
127.0.0.1	localhost

it will produce such error: 
```
OSError: [Errno 98] Address already in use
>>> 
```

and if change this code 
```
ARGS.add_argument(
    '--host', action='store', dest='host',
    default='localhost', help='Host name')
```
to 127.0.0.1  , it will work fine now .

**Comment by gvanrossum** [comment]
You could just run the script with `--host 127.0.0.1` to the same effect,
but you probably have a different problem (maybe you didn't kill an earlier
run). Generally the fix for this issue would be to add reuse_port=True to
the call to start_server() though.

**Comment by a358003542** [comment]
OK, i think we can close this issue.

**Comment by GMLudo** [comment]
@a358003542: just in case, you could launch `sudo netstat -puante | grep 54321` to see if 54321 port is already used before.

**Comment by a358003542** [comment]
@GMLudo: wa , this command shows so many information. 

no , there is no 54321 string.
