### ISSUE TITLE
transport._call_connection_lost(exc) never gets called

### ISSUE THREAD

**Issue by SzieberthAdam** [python/asyncio#301]
Hi,

By investigating the issue reported by Łukasz Kawczyński in aaugustin/websockets#84, it seems that there could be situations when the transport never gets closed, but instead keeps sending `socket.send() raised exception` warnings forever. The server is unable to accept new connections once this happens.

Consider the following server/client code:
```
# server.py
import asyncio

import sys
import logging
loghandler = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=logging.DEBUG, handlers=[loghandler])
loop = asyncio.get_event_loop()
loop.set_debug(True)

async def client_connected_cb(client_reader, client_writer):
  n = 0
  while True:
    msg = str(n).encode() + b'\n'
    client_writer.write(msg)
    n += 1
    #await asyncio.sleep(0)
    #if client_reader.exception():
    #  break
    #if client_writer.transport._conn_lost:
    #  break

coro = asyncio.start_server(client_connected_cb,
  host='localhost', port=8765, loop=loop)

server = loop.run_until_complete(coro)
loop.run_forever()
```
```
# client.py
import asyncio

import sys
import logging
loghandler = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=logging.DEBUG, handlers=[loghandler])
loop = asyncio.get_event_loop()
loop.set_debug(True)

async def client(loop):
  reader, writer = await asyncio.open_connection(
      host='localhost', port=8765, loop=loop)
  while True:
    msg = (await reader.readline()).strip()
    n = int(msg.decode())
    print(n)

loop.run_until_complete(client(loop=loop))
```

*Usage: Kill the clint side with `Ctrl+C` and make sure to kill the server as well shortly thereafter to be able to read the server log.*

It seems that the `while` loop in `client_connected_cb` keeps pushing the writes without any chance to know that the connection is lost.

Here, `transport.write()` gets a `ConnectionResetError` and calls `transport._fatal_error(exc)`. In that method the exception is passed to the logger, and `transport._force_close(exc)` is called (module: `asyncio.selector_events`). In that method `transport._call_connection_lost(exc)` gets scheduled by the event loop (`loop.call_soon`). `transport._call_connection_lost()` is responsible to tear down the transport and call `protocol.connection_lost(exc)`.

Unfortunately, the event loop never gets to call `transport._call_connection_lost()`. By uncommenting `await asyncio.sleep(0)` in the server side connection callback the scheduler gets a small breath to call it and close the transport. This way the server can accept new connections once one is lost, but still keeps sending the warnings forever. This seems a silly and nontrivial way to enforce the "right" behavior. I don't see the reason why `transport._call_connection_lost()` can't get called directly in `transport._force_close()`.

When somehow `transport._call_connection_lost()` does its job, `client_connected_cb()` can obtain the exception by checking for a truthy `client_reader.exception()` and be able to stop or break from the `while` loop. Still this also seems nontrivial and hacky to me. Naively, I would expect to simply get a `ConnectionResetError` exception when failed to write. Unfortunately that exception gets well hidden in the `asyncio` mechanism.

Another way to break from the `while` loop is to check if `0 <= client_writer.transport._conn_lost`. Since it involves a private property, i would not prefer to do it.

Thanks for your answer in advance!

Best regards,
Ádám.

**Comment by gvanrossum** [comment]
I don't see a bug in asyncio here. The proper way to write this code is to call `await client_writer.drain()` after each write, or after each small number of writes.

**Comment by SzieberthAdam** [comment]
Unfortunately I tried that but it does not solve the issue. Missed to add it to the posted example.

**Comment by gvanrossum** [comment]
Try the latest asyncio version from the repo. IIRC we fixed some subtle
issue related to drain() recently.

**Comment by SzieberthAdam** [comment]
Nice, `_drain_helper()` raises the exception properly. I was using the 3.5.0 code. Should have test the repo version before posting. Thanks for your time and answer!
