### ISSUE TITLE
asyncio in 3.5.1 breaks cython test-suite (or vice versa)

### ISSUE THREAD

**Issue by xnox** [python/asyncio#308]
Cython test suite has tests specifically for asyncio 3.5 generators, as far as I understand.

Compiling cython 0.23.4 fails with python 3.5.1
(see https://launchpad.net/ubuntu/+source/cython/0.23.4-0ubuntu1 click on a desired arch, then click on buildlog, direct link for e.g. amd64 buildlog is https://launchpadlibrarian.net/233177552/buildlog_ubuntu-xenial-amd64.cython_0.23.4-0ubuntu1_BUILDING.txt.gz )

Reverting the changes to asyncio module introduced between 3.5.0 and 3.5.1 makes said test pass:

```
======================================================================
FAIL: runTest (__main__.EndToEndTest)
End-to-end asyncio_generators
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1417, in runTest
    self.assertEqual(0, res, "non-zero exit status")
AssertionError: 0 != 1 : non-zero exit status
```

Now, this could be a bug in cython, cython test-suite, or the asyncio module... However, I cannot quite determine what's wrong is going on.

I guess I should also try running bisect with git checkouts of asyncio module... Would you be able to help with this? I'll report this bug to cython upstream too...

**Comment by gvanrossum** [comment]
I recommend that you ask help from the Cython project first -- it's their
tests that are breaking.

**Comment by xnox** [comment]
Fixed in https://github.com/cython/cython/commit/7eed8d8ff9c872bc993a37438beca0f98e3aba38
