### ISSUE TITLE
connect_read_pipe causes "Exception ignored in:" on program exit

### ISSUE THREAD

**Issue by sbourdeauducq** [python/asyncio#314]
The following program prints "Exception ignored in:" when exiting. I am using Python 3.5.1. In my real application, the problem also occurs with a inherited pipe file descriptor from the parent process (wrapped with ``open(fd, "rb", 0)``) instead of ``sys.stdin``.
```python
import asyncio
import sys

loop = asyncio.get_event_loop()
reader = asyncio.StreamReader(loop=loop)
reader_protocol = asyncio.StreamReaderProtocol(reader, loop=loop)

# commenting this out makes the message disappear
loop.run_until_complete(loop.connect_read_pipe(lambda: reader_protocol, sys.stdin))

loop.close()

# to demonstrate message happens at exit
import time
time.sleep(5)
```

**Comment by Martiusweb** [comment]
Hi,

Can you run your code with the environment variable ``PYTHONASYNCIODEBUG=1``:

    PYTHONASYNCIODEBUG=1 python your_test_case.py

It seems that since you don't close anything else than the loop, an exception happens in a __del__, and prevent the actual RessourceWarning to be displayed.

**Comment by sbourdeauducq** [comment]
I had already tried ``PYTHONASYNCIODEBUG=1``, but since it didn't print anything more I thought I was setting it wrong. Same behavior on 3.5.1 and 3.4.4rc1.

**Comment by sbourdeauducq** [comment]
Ping

**Comment by gvanrossum** [comment]
What's the FULL exception? Is there anything after the "Exception ignored in:"? Usually there's more there.

Your  problem is closing the loop while it's still referenced, that's not a good idea. E.g. you may want to close the pipe first.

**Comment by sbourdeauducq** [comment]
No, there isn't more. This bug causes Python to print exactly that: "Exception ignored in:"

**Comment by sbourdeauducq** [comment]
Modifying the program to close the pipe AND THEN run a dummy coroutine makes the message disappear.

```python
import asyncio
import sys

loop = asyncio.get_event_loop()
reader = asyncio.StreamReader(loop=loop)
reader_protocol = asyncio.StreamReaderProtocol(reader, loop=loop)

r, w = loop.run_until_complete(loop.connect_read_pipe(lambda: reader_protocol, sys.stdin))
r.close()

@asyncio.coroutine
def workaround():
    yield
loop.run_until_complete(workaround())

loop.close()
```

**Comment by vxgmichel** [comment]
I noticed this error a while ago. It is triggered by the [following line](https://github.com/python/asyncio/blob/master/asyncio/unix_events.py#L381) in [unix_events](https://github.com/python/asyncio/blob/master/asyncio/unix_events.py):
```
warnings.warn("unclosed transport %r" % self, ResourceWarning)
```
Full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 383, in __del__
    warnings.warn("unclosed transport %r" % self, ResourceWarning)
  File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 336, in __repr__
    self._fileno, selectors.EVENT_READ)
  File "/usr/local/lib/python3.5/asyncio/selector_events.py", line 35, in _test_selector_event
    key = selector.get_key(fd)
AttributeError: 'NoneType' object has no attribute 'get_key'
```
At that time, `_UnixReadPipeTransport()._loop._selector` is None, so `get_key` fails.

However, I'm not sure why the exception is not printed completely.
