### ISSUE TITLE
remove duplicate bind addresses in create_server

### ISSUE THREAD

**Issue by sbourdeauducq** [python/asyncio#315]
Detecting and removing duplicate bind addresses is difficult outside of asyncio, as name resolution happens in the latter.

For example, in my application, I'm always binding to "127.0.0.1" in addition to addresses passed by the user, and without this patch it would fail with "Address already in use" if the user attempted to bind to "localhost". 

```
diff --git a/asyncio/base_events.py b/asyncio/base_events.py
index 4505732..041bd2d 100644
--- a/asyncio/base_events.py
+++ b/asyncio/base_events.py
@@ -909,7 +909,7 @@ def create_server(self, protocol_factory, host=None, port=None,
                                                   flags=flags)
                   for host in hosts]
             infos = yield from tasks.gather(*fs, loop=self)
-            infos = itertools.chain.from_iterable(infos)
+            infos = set(itertools.chain.from_iterable(infos))
 
             completed = False
             try:
```

**Comment by asvetlov** [comment]
Looks like you get an issue when call 

    loop.create_server(['127.0.0.1', '127.0.0.1'], port=1234)

or 

    loop.create_server(['127.0.0.1', 'localhost'], port=1234)

Removing duplicates on asyncio side is possible but you really may do it in your code, isn't it?
For more complex scenarios not limited to *localhost* you also may resolve DNS name by `loop.getaddrinfo(...)` call.

I really consider asyncio as low-level library which should not care about cases like your issue while it can be done on application level.

**Comment by sbourdeauducq** [comment]
Doing it in the application requires duplicating the name resolution code from ``create_server`` and converting the addresses back to textual representation before ``asyncio`` resolves them again.

Doing it in ``asyncio`` is a subtle change of behavior to something I believe most real-world applications will be indifferent to or benefit from, and a 4-character patch.

**Comment by gvanrossum** [comment]
I think this is a reasonable feature to request. I haven't looked at the patch.

**Comment by 1st1** [comment]
Agree. @sbourdeauducq do you have a patch?

**Comment by sbourdeauducq** [comment]
Yes, it's in my first post.

**Comment by 1st1** [comment]
The patch looks fine, please create a PR.

**Comment by asvetlov** [comment]
Ok, I'm fine with the proposal but a test is required.

**Comment by haypo** [comment]
If I recall correct, we decided to not remove duplicates hosts, when
we added support for multiple hosts.

**Comment by sbourdeauducq** [comment]
I do not see a discussion of this in the PR.
https://bugs.python.org/issue23630

I was already arguing for the removal of duplicate hosts (see 3rd message in the PR), but that detail was somehow dropped in the refactored patch that @fallen submitted.

**Comment by fallen** [comment]
I also recall a discussion where it was agreed not to remove duplicates. I guess it was on IRC and I don't keep IRC logs unfortunately.

**Comment by sbourdeauducq** [comment]
What are the arguments against?

**Comment by 1st1** [comment]
@haypo @fallen I vaguely remember that we discussed that removing duplicates from the initial list of hosts is a bad idea. I.e. if a user calls `await create_server(proto, ['localhost', 'localhost'], 80)` it's their fault.

What @sbourdeauducq wants to fix is an entirely different matter.  If you pass a list of hosts and some of them happen to resolve to same address, you have no way of fixing that error.

@sbourdeauducq please submit a PR with a unittest.

**Comment by gvanrossum** [comment]
FWIW, discussions on IRC are irrelevant unless some reports back to a
mailing list or an issue.

**Comment by fallen** [comment]
Patch looks OK to me.

**Comment by sbourdeauducq** [comment]
http://bugs.python.org/issue26338

**Comment by 1st1** [comment]
Committed. Thanks, Sebastien!
