### ISSUE TITLE
Needs example of implementing `async with`

### ISSUE THREAD

**Issue by dalanmiller** [python/asyncio#316]
Looking for examples of how to implement a class with the `__aenter__` and `__aexit__` dunder methods for an asynchronous opening of a file or socket.

**Comment by 1st1** [comment]
asyncio only implements support for `async with` for synchronization primitives: https://github.com/python/asyncio/blob/master/tests/test_pep492.py#L40

**Comment by dalanmiller** [comment]
This is what I was referring to => https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with

This doesn't mention being limited to just synchronization primitives?

**Comment by 1st1** [comment]
> This doesn't mention being limited to just synchronization primitives?

`async with` is a feature of Python language. `__aenter__` and `__aexit__` are part of the protocol that supports it.

In asyncio we only implement support for `async with` for locks, events etc.  aiohttp, for instance, implements it for HTTP sessions, see http://aiohttp.readthedocs.org/en/stable/#getting-started

If you have an idea on how we can add support for `async with` in for other asyncio parts, please open a PR.

**Comment by dalanmiller** [comment]
Apologies @1st1 I was mistaken. What I was looking for were for examples of not how `__aexit__` and `__aenter__` for `asyncio` but how I _should_ implement these myself for my own Classes. Particularly, I was trying to avoid the `await` in `async with await .... as`. There isn't a lot of documentation / examples of `asyncio` and I was trying to get some more information on what the purpose of each of the dunder methods are.

**Comment by 1st1** [comment]
NP!

> What I was looking for were for examples of not how __aexit__ and __aenter__ for asyncio but how I should implement these myself for my own Classes. Particularly, I was trying to avoid the await in async with await .... as. 

Right. `async with await` is an anti-pattern.  Just implement `async def __aenter__` and `async def __aexit__` methods for you class and you'll be able to use it in `async with`.

Unfortunately this issue tracker is used primarily for asyncio bugs/enhancements, so I recommend you to use python-list mailing list (or IRC) for any questions re async/await.
