### ISSUE TITLE
Add async for facility to as_completed()

### ISSUE THREAD

**Issue by asvetlov** [python/asyncio#317]
For now `as_completed` should be used as
```
for f in as_completed(fs):
    result = yield from f  # The 'yield from' may raise
    # Use result
```

I propose adding the following:
```
async for result in as_completed(fs):
    # Use result
```
Functionality of the latter snippet is shrinked a bit: an exception from future object stops the whole loop but it is maybe desired behavior, user always may return to explicit future awaiting if needed.

Implementation is pretty straightforward: hide current `as_completed` to `_as_completed`, return custom iterator object on `as_completed` call with support both `__iter__/__next__` and `__aiter__/__anext__` protocols.

I would prepare a Pull Request after getting preliminary agreement.

**Comment by gvanrossum** [comment]
It's a fine idea. I don't know of many places where as_completed() is
actually used though. Do you use it aiohttp or some of your apps?

**Comment by 1st1** [comment]
Wouldn't it be a bit confusing if `as_completed` works with both `for` and `async for`?

> Functionality of the latter snippet is shrinked a bit: an exception from future object stops the whole loop but it is maybe desired behavior, user always may return to explicit future awaiting if needed.

This is an important difference though.  It's obvious how to handle exceptions with a `for` loop:

```python
for f in as_completed():
   try:
     await f
```

If you're using `async for` syntax and then decide to handle exceptions, you'll have to **revert** your code back to using regular `for`.  TBH, I think this change will only introduce confusion.

**Comment by asvetlov** [comment]
@gvanrossum actually I never used `as_completed` in my code but I've get a question about receiving messages from several async sources: redis/rabbitmq and websocket.

User can split incoming sequence by message type (using `isinstance` check).

As an alternative he should create two tasks: one for receiving pub/sub messages and other for websocket incoming message handling.

Honestly I don't like the first solution but maybe it makes sense -- I'm not sure.

**Comment by asvetlov** [comment]
If nobody have an evidence of `as_completed` usage rejecting or postponing the issue is fine to me.

P.S. I never used `wait` also -- only `wait_for` and `gather`. 

But found `shield` very useful -- in `aiopg` Postgres driver on cancelling SQL request by timeout the cancellation coroutine should be finished by sending graceful shutdown event to SQL server regardless on future cancellation of outer task which may have own timeout.

**Comment by gvanrossum** [comment]
Honestly, wait() and as_completed() are very low-level APIs that were
added to be similar to concurrent.futures. They have not been very
successful. Let's close this as a won't fix.
