### ISSUE TITLE
Merge fix of issue 25647 (return of asyncio.coroutine from asyncio.coroutine doesn't work with enabled asyncio debug)

### ISSUE THREAD

**Issue by rutsky** [python/asyncio#324]
This [issue](https://bugs.python.org/issue25647) has patch which is already reviewed.
However I see that fix is not yet integrated in this repo or CPython 3.4 branch.

@1st1, can you merge it?

/cc @himikof

**Comment by 1st1** [comment]
Done! Thanks for the patch!

**Comment by 1st1** [comment]
Committed in CPython in [`fd21f162e377`](https://hg.python.org/cpython/rev/fd21f162e377/)

**Comment by rutsky** [comment]
@1st1, thanks!

Will you backport these changes to 3.4 branch?

Also, is another minor release of 3.4 is planned (i.e. 3.4.5)?

**Comment by gvanrossum** [comment]
New 3.4 releases will only go out when security patches necessitate
it, and then only as source releases. In general we no longer backport
non-security things to 3.4.

**Comment by 1st1** [comment]
I think that 3.4 is in security patches only mode now. @haypo, @gvanrossum am I right?
