### ISSUE TITLE
Resuming protocol in set_write_buffer_limits

### ISSUE THREAD

**Issue by 1st1** [python/asyncio#329]
While working on uvloop I stumbled upon `transports._FlowControlMixin.set_write_buffer_limits()` method:

```python
def set_write_buffer_limits(self, high=None, low=None):
    self._set_write_buffer_limits(high=high, low=low)
    self._maybe_pause_protocol()
```

Shouldn't we also add a call to `_maybe_resume_protocol()` here?

**Comment by gvanrossum** [comment]
It does look as if it would add symmetry, which is often a good thing.
Though it likely won't affect any real-world code...?

**Comment by 1st1** [comment]
> Though it likely won't affect any real-world code...?

Not sure :(  I guess some convoluted code, theoretically, can expect that a call to `set_write_buffer_limits` with a higher limit will resume the protocol.

I can draft a patch if you think we should fix this.

**Comment by gvanrossum** [comment]
Honestly since nobody's asked about it I'd say let's leave well enough
alone.

**Comment by 1st1** [comment]
OK
