### ISSUE TITLE
Add get_exeption_handler()

### ISSUE THREAD

**Issue by sametmax** [python/asyncio#340]
We have set_exeption_handler(), but no getter. Currently we use _exception_handler to obtain the previous one, but it's already causing [some troubles](https://github.com/MagicStack/uvloop/issues/3#issuecomment-216704907). 

A property would actually be even more idiomatic than a get/set method.

**Comment by 1st1** [comment]
Congrats, we now have the `get_exception_handler` method. I'll add it to uvloop tomorrow.
