### ISSUE TITLE
Add github automatic code checkers + testing under Winows.

### ISSUE THREAD

**Issue by socketpair** [python/asyncio#350]
https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml allows to check under M$ Windows. Or I'm wrong ?

https://github.com/integrations/appveyor

And more generally, https://github.com/integrations - this can improve quality of code.

**Comment by 1st1** [comment]
Windows CI has landed in https://github.com/python/asyncio/commit/0788e04657e1f58f4bb4079700bf437db92ba125

**Comment by GMLudo** [comment]
Thank you @1st1 for the setup, everything seems to be ok.

I think we can close this issue. Don't hesitate to re-open if something is missing.

Have a nice day.
