### ISSUE TITLE
SO_REUSEPORT is defined but not implemented on Android

### ISSUE THREAD

**Issue by xdegaye** [python/asyncio#352]
See Python issue 26858 [1].  The following patch defines is_android in a backward compatible way to support the changes in Python issue 26858 [1].

[1] http://bugs.python.org/issue26858.

    diff -r 2a742cf69c8d asyncio/test_support.py
    --- a/asyncio/test_support.py   Sun May 22 09:02:27 2016 +0200
    +++ b/asyncio/test_support.py   Sun May 22 10:11:48 2016 +0200
    @@ -102,6 +102,9 @@

     is_jython = sys.platform.startswith('java')

    +is_android = (hasattr(platform, 'android_ver') and
    +              bool(platform.android_ver()[0]))
    +
     def gc_collect():
         """Force as many objects as possible to be collected.

**Comment by 1st1** [comment]
Closing this one now.
