### ISSUE TITLE
getaddrinfo doesn't accept port service names

### ISSUE THREAD

**Issue by 1st1** [python/asyncio#353]
`socket.getaddrinfo` and `loop.getaddrinfo` in Python 3.5.1 can accept service names for its `port` argument, i.e.

```python
>>> socket.getaddrinfo('127.0.0.1', 'http')
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 80)),
 (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 80))]
```

In 3.5.2 with our custom `_ipaddr_info` such calls will fail with an exception:

```python
>>> import asyncio, socket
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(loop.getaddrinfo('127.0.0.1', 'http', type=socket.SOCK_STREAM))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yury/dev/py/asyncio/asyncio/base_events.py", line 589, in getaddrinfo
    info = _ipaddr_info(host, port, family, type, proto)
  File "/Users/yury/dev/py/asyncio/asyncio/base_events.py", line 108, in _ipaddr_info
    port = int(port)
ValueError: invalid literal for int() with base 10: 'http'
```

/cc @ajdavis

**Comment by gvanrossum** [comment]
Honestly I thought that such service names were a thing of the past. But ah well...

**Comment by 1st1** [comment]
Looks like we need to use https://docs.python.org/3/library/socket.html#socket.getservbyname if we can't cast port to an int.

**Comment by gvanrossum** [comment]
You mean a numeric string like '80' would also be accepted?

**Comment by 1st1** [comment]
Yes, and event `b'80'`, since `socket.getaddrinfo` accepts it. Apparently people use that.

**Comment by ajdavis** [comment]
This little project still has more corners of socket programming to teach me! I've dealt with '80' and b'80' already, this last patch also handles 'http' and b'http'.

**Comment by 1st1** [comment]
Closing this issue -- the relevant PR has been merged.
