### ISSUE TITLE
asyncio udp

### ISSUE THREAD

**Issue by valdemarpavesi** [python/asyncio#360]
hello,

python 3.5.1

I am using asyncio udp , and I am loosing messages.  

monitoring by tcpdump I got Packets: 475  UDP   and only 446 was delivered to :

  def datagram_received(self, data, addr):
        # add to queue 
        asyncio.async(self.send_message(data))

++++++
#########################################
class UDPProtocolServerTraffica:
    
    def __init__(self):
        self.transport = None
        # heart beat timer
        self.HEARTBEAT_TIMEOUT = 10.0
        self.REPORTSHOWTOTAL_TIMEOUT=60.0
        self.ReportCount = 0
        self.queue = asyncio.Queue()
        self._ready = asyncio.Event()
        asyncio.async(self._send_messages())

    @asyncio.coroutine
    def _send_messages(self):
        """ Send messages to elasticserver as they become available. """
        yield from self._ready.wait()
        print_ts("Ready!")
        while True:
            data = yield from self.queue.get()
                  report_fns_mme_mm(data,Counter)
                 
 
    def connection_made(self, transport):
        self.transport = transport
        # traffica startup message
        self.transport.sendto(self.MSG_UDP_HEARTBEAT, (fns_remote_host, fns_remote_port))
        # start 10 seconds timeout timer
        self.h_timeout = asyncio.get_event_loop().call_later(self.HEARTBEAT_TIMEOUT, self.timeout_heartbeat)
        # show total report
        self.h_timeout = asyncio.get_event_loop().call_later(self.REPORTSHOWTOTAL_TIMEOUT, self.timeout_report_showtotal)
        self._ready.set()
 
    def datagram_received(self, data, addr):
        #fns_mmdu_ipaddr = addr [0]
        #fns_mmdu_port = addr [1]

        # schedules the execution 
        asyncio.async(self.send_message(data))
           
    def error_received(self, exc):
        print('Error received:', exc)

    def connection_lost(self, exc):
        print('stop', exc)

    def timeout_heartbeat(self):
        self.transport.sendto(self.MSG_UDP_HEARTBEAT, (fns_remote_host, fns_remote_port))
        self.h_timeout = asyncio.get_event_loop().call_later(self.HEARTBEAT_TIMEOUT, self.timeout_heartbeat)
        print('queue size ',self.queue.qsize())
 
    def timeout_report_showtotal(self):
        self.h_timeout = asyncio.get_event_loop().call_later(self.REPORTSHOWTOTAL_TIMEOUT, self.timeout_report_showtotal)
        self.displayReportTotalCount()
        

    def displayReportTotalCount(self):
        print_ts('total reports:' + str(self.ReportCount))

    @asyncio.coroutine
    def send_message(self, data):
        """ Feed a message to the sender coroutine. """
        yield from self.queue.put(data)

 

regards!
valdemar

**Comment by ZhukovAlexander** [comment]
Hi, @valdemarpavesi. First,[ UDP is not reliable](https://en.wikipedia.org/wiki/User_Datagram_Protocol#Reliability_and_congestion_control_solutions), wo without additional machinery, implemented on the application level, there is no guarantee, that you will receive all packets and/or in the same order, that they were sent. Furthermore, it seems that in the code fragment above there is no handling of lost messages implemented. You could switch to TCP, or implement some custom algorithm to handle packet loss, based on Acks/Nacks and sequence numbers.

**Comment by gvanrossum** [comment]
I think this was resolved in some other forum.

**Comment by valdemarpavesi** [comment]
Hello,

yes,  it is solved.

asyncio is working perfectly !  I do have another 5 projects.

at moment single machine with 2 cpu ,4 giga memory,  600 UDP requests per second.

600 bytes  and  upload to elastic stack.

![image](https://cloud.githubusercontent.com/assets/10376101/20932798/7ec8fc68-bb9b-11e6-9c39-b74e85c6bc6a.png)


thanks and regards!

Valdemar
