### ISSUE TITLE
asyncio.sslproto.SSLProtocol (NameError: name 'base_events' is not defined)

### ISSUE THREAD

**Issue by doko42** [python/asyncio#371]
[forwarded from https://bugs.debian.org/827453]

"""
when trying to use py2dsp I get the following error:

E: py2dsp base_events:1148: Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fed96ce9b00>
transport: <_SelectorSocketTransport fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 707, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <bound method _SSLProtocolTransport.__del__ of
<asyncio.sslproto._SSLProtocolTransport object at 0x7fed96ce9b38>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 328, in __del__
    self.close()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 319, in close
    self._ssl_protocol._start_shutdown()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 542, in
_start_shutdown
    self._write_appdata(b'')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 547, in _write_appdata
    self._process_write_backlog()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 651, in
_process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 658, in _fatal_error
    if isinstance(exc, base_events._FATAL_ERROR_IGNORE):
NameError: name 'base_events' is not defined
"""

Fixed by:

--- a/Lib/asyncio/sslproto.py
+++ b/Lib/asyncio/sslproto.py
@@ -5,6 +5,7 @@ try:
 except ImportError:  # pragma: no cover
     ssl = None
 
+from . import base_events
 from . import compat
 from . import protocols
 from . import transports

**Comment by gvanrossum** [comment]
Already fixed by a2427ba708e7376c7572e001b3eb33bbd7c8fe3b.

**Comment by ssbarnea** [comment]
Any plans to release this? We just hit it during a late stage migration to Python 3.5.

**Comment by 1st1** [comment]
It's fixed and will be released with the next version of CPython 3.5 (in a few months).

As an alternative, you can use [uvloop](https://github.com/MagicStack/uvloop) -- it has it's own SSL implementation.
