### ISSUE TITLE
Asyncio Error Bubbling being prevented.

### ISSUE THREAD

**Issue by ADetectionAlgorithm** [python/asyncio#377]
Hello!

I am creating a task, and at some point during the task, there is an Exception.  (My Doing)  How would I go about catching this exception?

example:

```
                try:
                    self.loop.create_task(plugin.on_command(message, message_type, message_context))
                except exceptions.TerminateSignal:
                    raise
                except exceptions.RestartSignal:
                    raise
```
I tried using a try accept loop to check for the exceptions, but it seems asyncio doesn't pass exceptions up the chain.

I am trying to use an error as a restart / shutdown signal, but asyncio seems to be preventing it from bubbling up high enough.

```
Task exception was never retrieved
future: <Task finished coro=<PBPlugin.on_command() done, defined at {project folder}/plasmaBot/plugin.py:81> exception=RestartSignal()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/{project folder}/plasmaBot/plugin.py", line 165, in on_command
    response = await handler(**handler_kwargs)
  File "{project folder}/plasmaBot/plugins/bot_operation.py", line 77, in cmd_restart
    self.bot.restart()
  File "{project folder}/plasmaBot/bot.py", line 65, in restart
    raise exceptions.RestartSignal
plasmaBot.exceptions.RestartSignal
```

If anyone could help, that would be appreciated 👍

**Comment by Martiusweb** [comment]
A task is running asynchronously, hence, the exception is not bubbled when the task created as it is not yet running. You have to await the task to get its result.

Please note that this is the bug tracker, aimed at tracking bug in the implementation of asyncio, not helping users. The python-tulip (https://groups.google.com/forum/#!forum/python-tulip) list is the place to asks those questions.
