### ISSUE TITLE
StreamReader.readuntil() weirdness

### ISSUE THREAD

**Issue by kaniini** [python/asyncio#379]
Based on my understanding of StreamReader.readuntil(), the following asserts should be true for the code below (`reader` is a `StreamReader` object associated to a stream):

```python
found_header_sentinel = False

while not found_header_sentinel:
    try:
        trailing = (yield from reader.readuntil(b'\x02'))[-1:1]
        assert len(trailing) == 1
        assert trailing == b'\x02'
        found_header_sentinel = True
    except asyncio.IncompleteReadError:
        print('incomplete read error')
        exit()
```

Unless an `asyncio.IncompleteReadError` (or maybe `asyncio.LimitOverrunError`) exception is thrown, `trailing` should always be `b'\x02'`.  However, under moderate load this is occasionally not the case, and the connection itself is fine (in fact looping until this is the case works out, but that makes me nervous that some requests may be dropped).   In the cases where `trailing` is not `b'\x02'`, `trailing` is always `b''` (which was odd to me until I observed that `b''[-1:1] == b''` (is that a language issue in and of itself?  `b[-1]` rightly raises `IndexError`.)).

Is this intentional and therefore a documentation error, or is this a bug in `asyncio`?

**Comment by kaniini** [comment]
theory: other peer calls `shutdown(2)` on it's socket, but python fails to throw `asyncio.IncompleteReadError`.

**Comment by Elizafox** [comment]
Yes, asyncio is mimicking the behaviour of socket.recv() on EOF (no data on the pipe, connection closed already), but in this context IMO it should really raise that exception with partial being set to b''.

**Comment by 1st1** [comment]
cc @socketpair

**Comment by socketpair** [comment]
1. I'm author of `readuntil()` code and I'm sure that it works right. Can you provide minimal code that reproduce  this bug ? I mean bug appearing only at moderate load.
2. This code will never pass assertions, since:

```
In [3]: qwe='asd'
In [4]: qwe[-1:1]
Out[4]: ''
In [5]: qwe[-1:]
Out[5]: 'd'
```

**Comment by kaniini** [comment]
@socketpair thanks for pointing out my mistake, i apologize for the noise.  we are testing the `[-1:]` change now and that should resolve it.
