### ISSUE TITLE
Provide a way to react to policy or loop change

### ISSUE THREAD

**Issue by sametmax** [python/asyncio#382]
Right now if one of your object has a reference to a loop, and something changes the current event loop or even the policy, very hard to debug problems occur.

It would be useful to be able to setup something (an event/signal system or just a bare callback) so we can register some code to be run when a new loop is set or a new policy is set.

The main usage for us would be to check if we have a different loop than the current one, and warn locally about the consequences before something cryptic like " got Future <Future pending> attached to a different loop" raises.

Another possible usage is to be able to automatically reuse any new loop set. Or to create a lazy program that starts to use a loop only once it's been set.

**Comment by 1st1** [comment]
> It would be useful to be able to setup something (an event/signal system or just a bare callback) so we can register some code to be run when a new loop is set or a new policy is set.

How/why people create more than one loop?

> Another possible usage is to be able to automatically reuse any new loop set. Or to create a lazy program that starts to use a loop only once it's been set.

The idea is to always use `asyncio.get_event_loop()`.

**Comment by sametmax** [comment]
@1st1:
> How/why people create more than one loop?

 usually by mistake, because several libs create a new one. My particular use case would be to set a callback calling the warning module so I could tell my dev "something is fishy here, lool this up". 

> The idea is to always use asyncio.get_event_loop().

You do that only at object init (at least most classes in the stdlib do that), then hold the loop in a ref.

**Comment by vxgmichel** [comment]
For what it's worth, you can define your own policy and make it stricter (or add warnings):

```python
import asyncio

class StrictEventLoopPolicy(asyncio.DefaultEventLoopPolicy):
    def new_event_loop(self):
        if self._local._set_called:
            raise RuntimeError('An event loop has already been created')
        return super().new_event_loop()
    
asyncio.set_event_loop_policy(StrictEventLoopPolicy())

loop = asyncio.get_event_loop()
asyncio.new_event_loop()  # Oops
```

**Comment by sametmax** [comment]
Good to know.

**Comment by 1st1** [comment]
I think what @vxgmichel is suggesting makes a lot of sense. Closing the issue, as adding new APIs to policies seems highly unlikely.
