### ISSUE TITLE
Provide a standard way to switch protocol

### ISSUE THREAD

**Issue by urbaniak** [python/asyncio#388]
There should be a way to switch protocol in already connected transport, just like HTTP 101 case, it may be useful when switching http to websockets protocol.

Currently it's done by accessing the private property on a transport, like here aiopyramid's gunicorn worker is doing (https://github.com/housleyjk/aiopyramid/blob/8aef5f4f8c823d138f36b68df2ad40a8b5adb6a3/aiopyramid/websocket/config/gunicorn.py#L126.).

**Comment by 1st1** [comment]
@gvanrossum What do you think? Should we consider adding `transport.get_protocol()` and `transport.set_protocol()`?

**Comment by asvetlov** [comment]
IIRC protocol switch is very useful feature for upgrading raw socket up to tls also.

**Comment by GMLudo** [comment]
Might this feature help to implement protocols on the top of WebSockets like for SIP: https://tools.ietf.org/html/rfc7118 ?

Or I'm too much optimistic ? 

(The goal of this feature is to permit the Web browsers to use some raw sockets protocols through a proxy,  and in the same time, bypass most firewalls)

**Comment by gvanrossum** [comment]
Adding get/set_protocol sounds reasonable.

--Guido (mobile)

**Comment by 1st1** [comment]
@gvanrossum Should we allow to swap protocols only after `connection_made` is called, or make it simple and allow it at any time?

**Comment by gvanrossum** [comment]
I'm sorry, I have no bandwidth to think about this. I recommend doing the
thing that has obviously no errors, even if it's more constrained than the
thing that has no obvious errors.

**Comment by 1st1** [comment]
Alright, I think that we should allow to set a new proto at any time. This will be an advanced low-level feature anyways. I'll make a PR soon.

**Comment by 1st1** [comment]
Landed in https://github.com/python/asyncio/commit/32b8996e81cbb9756dea17a058f46557e5cfa691 and https://hg.python.org/cpython/rev/f12a59311885.

**Comment by gvanrossum** [comment]
What do you think about updating PEP 3156? Or is it too hopelessly behind?

**Comment by 1st1** [comment]
Would be cool to sync it with the docs. Maybe we can ask on python-dev for help?

**Comment by gvanrossum** [comment]
Please do!

**Comment by 1st1** [comment]
Sent an email to python-ideas. Although it's probably not the best mailing list for such requests, I think there are more people there who could help us with this.
