### ISSUE TITLE
100% CPU on asyncio.sleep(0)

### ISSUE THREAD

**Issue by dbivolaru** [python/asyncio#398]
A very interesting thing i am looking at is the fact that this code is using 100% CPU.

    while True:
        await asyncio.sleep(0)

I believe this should not be the case as it means the only way to avoid it is to use a non-zero constant like sleep(0.0001) or sleep(0.01) in the case PYTHONASYNCIODEBUG=1.

**Comment by 1st1** [comment]
`sleep(0)` simply returns immediately (but does that cooperatively, not blocking other coroutines). That's the expected behaviour.

**Comment by gvanrossum** [comment]
@dbivolaru What were you trying to accomplish? Given that this is expected, if you have no further questions can you close the bug?

**Comment by dbivolaru** [comment]
I converted a zmq-based project to asyncio/zmq.asyncio. There was some code running on a separate thread (third party library) so an internal segregation of zmq sockets using deque() was needed. This results in having to periodically check the deque object if it's empty or not and await on some I/O operations based on its elements. Including a sleep(0) in that loop is needed for not holding up other coroutines but doesn't help with the CPU usage unfortunately.

I think such scenarios are not that unrealistic especially if running more complex architectures and/or need to interface zmq with third-party libraries that run in a different thread.

I pinpointed and isolated the case to the simple example I gave above.

**Comment by gvanrossum** [comment]
Since you're polling in that scenario, you're just going to have to indicate yourself how often you want to poll. asyncio.sleep(0) means just that -- let any other tasks run and then come back here.

Is there some other system where sleep(0) means something else?

**Comment by dbivolaru** [comment]
@gvanrossum The question regarding other systems is a good one. I've just tested `yield tornado.gen.moment` and `yield tornado.gen.sleep(0)` to the same effect. Even C#'s 'await Task.Delay(0)` and `await Task.Yield()` seem to burn CPU also.

**Comment by gvanrossum** [comment]
OK, now I can sleep in peace. (Pun intended. ;-)
