### ISSUE TITLE
Discourage using fire-and-forget approach for creating new tasks

### ISSUE THREAD

**Issue by asvetlov** [python/asyncio#399]
Recently I saw several questions on StackOverflow about complaining: `asyncio` swallows a raised exception when a code is executed inside new task.

I could collect exact links to SO issues but the problem is obvious: newbies are tending to create a new task but never do `await task` at the end.

As result exceptions raised by a task are not displayed at all.

`PYTHONASYNCIODEBUG=x` definitely helps to find a _not awaited_ (aka _not joined_ if you are prefer threading terms) task but the doc is not clear about the issue.

Maybe warning section for `loop.create_task` doc will help but I honestly have no idea how write the warning text.

Suggestions?

**Comment by 1st1** [comment]
Don't we have `Task.__del__` that always complaints about unhandled exceptions?

**Comment by Martiusweb** [comment]
Isn't it related to the conversation in #397 ?

**Comment by asvetlov** [comment]
Yes, #397 has a good example for the issue.
Other thing is that warning raised by `Task.__del__` is very often just ignored as "no related to the problem" because it's raised later.
Honestly I don't know what to do here except adding a doc sentence like "A created task should be awaited somewhere later".
