### ISSUE TITLE
Attempting to get logs from asyncio produces no information at all.

### ISSUE THREAD

**Issue by AraHaan** [python/asyncio#400]
I was thinking that getting asyncio's 'logger' could produce information but it looks to me that I cant get the 'loggers' of 2 specific packages within 1 file.

```
    @staticmethod
    def set_up_loggers(loggers=None):
        """
        Logs Events from discord and/or asyncio stuff.
        :param loggers: Name of the logger(s) to use.
        :return: Nothing.
        """
        if loggers is not None:
            if loggers == 'discord':
                logger = logging.getLogger('discord')
                logger.setLevel(logging.DEBUG)
                handler = logging.FileHandler(filename='{0}{1}resources{1}Logs{1}discordpy.log'.format(sys.path[0],
                                                                                                       sepa),
                                              encoding='utf-8', mode='w')
                handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
                logger.addHandler(handler)
            elif loggers == 'asyncio':
                asynciologger = logging.getLogger('asyncio')
                asynciologger.setLevel(logging.DEBUG)
                handler = logging.FileHandler(filename='{0}{1}resources{1}Logs{1}asyncio.log'.format(sys.path[0],
                                                                                                     sepa),
                                              encoding='utf-8', mode='w')
                handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
asynciologger.addHandler(handler)
```
the discord logger works, but the asyncio one does not even if I remove the discord one entirely.
Maybe having a code ``example`` that works for 3.3, 3.4, 3.5, and 3.6 would be easier for those who wants to get the logs from asyncio and another package that actually works for both.

**Comment by asvetlov** [comment]
Please double check your code.
asyncio definitely **does** write into `'asyncio'` logger object, we have a lot of unittests for it.

Unfortunately your snippet is not full executable program, I cannot suggest what you did wrong.
asyncio does nothing special with logging, [Logging HOWTO](https://docs.python.org/3/howto/logging.html) and [Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html) have plenty of information about logging configuring.

But as quick and dirty solution you may add 
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
at very start of your program and see console output.

**Comment by AraHaan** [comment]
oh it might have been the handler variable being the sane name let me try it being renamed,
