### ISSUE TITLE
asyncio.Condition() in async with - dry

### ISSUE THREAD

**Issue by dbivolaru** [python/asyncio#401]
The following doesn't work. The equivalent in threading works.

    cond = asyncio.Condition()
    async with cond as c:
        await c.wait()

Considering the DRY principle, I think `asyncio/locks.py:_ContextManagerMixin.__aenter__` should return self instead of None:

        @coroutine
        def __aenter__(self):
            yield from self.acquire()
            return self

PEP492 actually doesn't mention anything about returning None. Iinstead it explicitly mentions `VAR = await aenter` in the pseudocode example [https://www.python.org/dev/peps/pep-0492/#new-syntax](url) and the example with lock is a few paragraphs afterwards.

Opinions? Did I miss anything?

**Comment by asvetlov** [comment]
Your PR brings non-consistence with `threading` module.
```
with threading.Condition() as lock:
    ...
```
returns *lock status*, not `Condition` itself.

*lock status* is just `bool` value: 
* `True` for acquired lock
* `False` for try to lock but failure for timeout reason.

Since `asyncio` has no timeout for locking the return value from context manager should be always `True`.
Now it's `None`, which is not bad -- nobody will check *always true* conditions.

**Comment by dbivolaru** [comment]
@asvetlov Thanks for the explanation. I should have looked more carefully in threading. It is still slightly against DRY and the way normal Contexts work. Will give the PEP's another read, if anything we should explicitly mention it in there if it's missing.

**Comment by asvetlov** [comment]
Technically context manager may return any object, not itself.
It's rare but possible and makes sense in some contexts.
Anyway, changing semantic to not compatible with `threading` is worse than supporting existing approach (while the approach maybe is not very obvious).

From other hand you may think that acquiring lock from condition is an operation which returns something new (an information about acquirement) but not condition instance itself.

**Comment by dbivolaru** [comment]
@gvanrossum I did not await a response but what I meant by DRY is that the last statement `#3` looks the cleanest.

    #1
    async with self.state[topic].conditions[id]:
        self.state[topic].conditions[id].wait()

    #2
    cond = self.state[topic].conditions[id]
    async with cond:
        cond.wait()

    #3
    async with self.state[topic].conditions[id] as c:
        c.wait()

But this won't allow returning the True/False return values when asnycio will have timeouts. If i might go even furher I would suggest to standardize both asyncio and threading on returning the object and introducing is_locked() API. This would align asyncio/threading Contexts with normal Contexts and make the API for (R)Lock and Condition (is_locked) more similar to Event (is_set).

    async with self.state[topic].conditions[id] as c:
        if c.is_locked():
            c.wait()

Compared to what one would write today, it is more elegant and simple.

    with self.state[topic].thread_conditions[id] as flag:
        if flag:
            self.state[topic].thread_conditions[id].wait()

or

    cond = self.state[topic].thread_conditions[id]
    with cond as flag:
        if flag:
            cond.wait()

Furthermore, one cannot specify the timeout in the `with` statement, so would probably be also a nice idea to implement a `__call__` wrapper that passes the parameters to acquire() so you can do something like this:

    with cond(timeout=1.0) as c:
        if c.is_locked():
            c.wait()

**Comment by gvanrossum** [comment]
FWIW, setting a timeout on a lock using a `with` statement is not supported
in threading. There is no way to pass the timeout (even though acquire()
does take a timeout). The idea would be absurd -- what would you do inside
the with statement if you didn't get the lock? So returning `True` there is
nonsense too. It should just return `None` to indicate that it has no
information.

**Comment by dbivolaru** [comment]
@gvanrossum Here is the working 'hack' to exemplify threading.

    import threading

    class CallableCondition(threading.Condition):
        def __call__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs
            return self

        def acquire(self):
            threading.Condition.acquire(*self.args, **self.kwargs)

        def is_locked(self):
            return self._lock.acquire(False)

        def __enter__(self):
            self._lock.__enter__()
            return self

    x = CallableCondition()
    with x(timeout=1.0) as f:
        if f.is_locked():
            f.wait(timeout=2.0)
