### ISSUE TITLE
unlink stale unix socket before binding

### ISSUE THREAD

**Issue by socketpair** [python/asyncio#425]
`loop.create_unix_server()` should remove socket at that path if it exists. Every application that wants to use unix socket server should do that. Why not to add code that removes unix socket before binding ?

It should:
1. Check if it is exists and that is UNIX socket (i.e. do `os.stat()`)
2. raise exception if removal failed, raise exception if this path exists but is not unix socket.
3. not even try to remove if path starts with zero byte (i.e. abstract unix socket)

**Comment by gjcarneiro** [comment]
What if you are trying, by mistake, to start a second instance of a server, with the previous one still running?  We want to catch that mistake, instead of silently removing the existing socket.

**Comment by socketpair** [comment]
All software that I see unlinks stale socket unconditionally. Can you show any one that checks for the other instance ? Also, seems the kernel checks if address already in use during `bind()` even when FS node is removed.

**Comment by 1st1** [comment]
+1 one to do this. @socketpair can you quickly make a PR (so that we can fix this before 3.6b2)?

**Comment by 1st1** [comment]
Although there is another approach: maybe the correct thing to do is to remove the socket file after we close the unix server? How Twisted/Tornado implement this?

**Comment by ZhukovAlexander** [comment]
@1st1 both Twisted and Tornado clean stale sockets before binding:

- https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/unix.py#L290
- https://github.com/tornadoweb/tornado/blob/master/tornado/netutil.py#L215

**Comment by socketpair** [comment]
@1st1 @ZhukovAlexander @gjcarneiro please review
