### ISSUE TITLE
asyncio.timeout() is missing documentation in Python 3.6

### ISSUE THREAD

**Issue by rutsky** [python/asyncio#427]
I see in [What’s New In Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html) that `asyncio.timeout` will be reintroduced in Python 3.6, but I don't see docs for it in 3.6.0b1 version in [official docs](https://docs.python.org/3.6/search.html?q=asyncio.timeout&check_keywords=yes&area=default).

/cc: @asvetlov

**Comment by asvetlov** [comment]
It was ripped out after inclusion.
But you can use [async_timeout](https://github.com/aio-libs/async_timeout) which is a clone of ripped version.

**Comment by rutsky** [comment]
Oh, I see... Then this issue is resolved, thanks for pointing on async_timeout!

**Comment by gvanrossum** [comment]
FWIW I removed it from the what's new. (If we end up adding something like
this back we'll update it again.)
