### ISSUE TITLE
mock.Mock() acts like a Future

### ISSUE THREAD

**Issue by popravich** [python/asyncio#454]
Since this changes 32edb29d5b0524e0da2400908093de5911f117f4 `unittest.mock.Mock` being detected
as `asyncio.Future`.
`asyncio.futures.isfuture` checks for private attribute `_asyncio_future_blocking`
to be not `None` and `Mock()` (without specs) returns new mock as this attribute.

The use case is here aio-libs/aioredis#161 — basically, function wrapped with `asyncio.coroutine` 
and set as `Mock`'s method `side_effect` started to raise `TypeError`.

**Comment by gvanrossum** [comment]
Is there something you want us to do?

--Guido (mobile)

**Comment by 1st1** [comment]
We can probably check `obj.__class__` for `_asyncio_future_blocking` attribute.

**Comment by popravich** [comment]
> Is there something you want us to do?

Yeah, it was more like FIY.
Maybe a little bit stricter check would be better.
Some use cases like implementing some kind of RPC with dynamic methods resolution might hit this case

**Comment by gvanrossum** [comment]
Can someone please translate the original post into an actionable issue for
me? I do not understand what the OP is asking.

**Comment by 1st1** [comment]
@gvanrossum Please see https://github.com/python/asyncio/pull/455.

**Comment by gvanrossum** [comment]
I'm not at all clear that a Mock should not be considered a Future. The clarification "Some use cases like implementing some kind of RPC with dynamic methods resolution" sounds awefully vague. Maybe there are just as many use cases that would break with this change?

**Comment by 1st1** [comment]
> Maybe there are just as many use cases that would break with this change?

`isinstance(unittest.mock.Mock(), asyncio.Future)` returns `False`. If we want to promote to use `isfuture` instead of `isinstance`, we should fix it.

**Comment by gvanrossum** [comment]
> isinstance(unittest.mock.Mock(), asyncio.Future) returns False. If we
want to promote to use isfuture instead of isinstance, we should fix it.

OK, that makes sense.

**Comment by gvanrossum** [comment]
Fixed by 26d01d796dccb365d3d6c00f8e35fe0d431b5abf (#455).

**Comment by popravich** [comment]
> `isinstance(unittest.mock.Mock(), asyncio.Future)` returns `False`

`isinstance(unittest.mock.Mock(asyncio.Future), asyncio.Future)` will return `True`.
But `isfuture(unittest.mock.Mock(asyncio.Future))` will return `False`.
Is that ok?

**Comment by 1st1** [comment]
Oh. Let me see how Mocks work.

**Comment by 1st1** [comment]
> But isfuture(unittest.mock.Mock(asyncio.Future)) will return False. Is that ok?

Fixed.
